name: Release Docker image

on:
  repository_dispatch:
    types:
      - release-triggered
  workflow_dispatch:
    inputs:
      custom_tag:
        description: 'Custom Docker image tag'
        required: false
      push_to_latest:
        description: 'Should push to latest'
        type: boolean
        default: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
      - run: "bundle install"

      - name: Release image
        run: script/release-workflow/run.sh
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
          CUSTOM_TAG: ${{ github.event.inputs.custom_tag }}
          PUSH_TO_LATEST: ${{ github.event.inputs.push_to_latest }}
